import type { Metadata } from 'next'
import { Roboto_Condensed } from 'next/font/google'
import './globals.css'


// const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto_Condensed({
  subsets:['latin'],
  weight:['100','300','400']
})



export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/dheereshagrwal/colored-icons@1.7.3/src/app/ci.min.css"
      />
      </head>
     
      <body style={roboto.style}>{children}</body>
    </html>
  )
}
